# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import products_pb2 as products__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in products_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SellerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
                '/products.SellerService/CreateAccount',
                request_serializer=products__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=products__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/products.SellerService/Login',
                request_serializer=products__pb2.LoginRequest.SerializeToString,
                response_deserializer=products__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/products.SellerService/Logout',
                request_serializer=products__pb2.LogoutRequest.SerializeToString,
                response_deserializer=products__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/products.SellerService/GetSellerRating',
                request_serializer=products__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=products__pb2.RatingResponse.FromString,
                _registered_method=True)
        self.RegisterItemForSale = channel.unary_unary(
                '/products.SellerService/RegisterItemForSale',
                request_serializer=products__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=products__pb2.RegisterItemResponse.FromString,
                _registered_method=True)
        self.ChangeItemPrice = channel.unary_unary(
                '/products.SellerService/ChangeItemPrice',
                request_serializer=products__pb2.ChangeItemPriceRequest.SerializeToString,
                response_deserializer=products__pb2.ChangeItemPriceResponse.FromString,
                _registered_method=True)
        self.UpdateUnitsForSale = channel.unary_unary(
                '/products.SellerService/UpdateUnitsForSale',
                request_serializer=products__pb2.UpdateUnitsRequest.SerializeToString,
                response_deserializer=products__pb2.UpdateUnitsResponse.FromString,
                _registered_method=True)
        self.DisplayItemsForSale = channel.unary_unary(
                '/products.SellerService/DisplayItemsForSale',
                request_serializer=products__pb2.DisplayItemsRequest.SerializeToString,
                response_deserializer=products__pb2.ItemListResponse.FromString,
                _registered_method=True)
        self.GetCategories = channel.unary_unary(
                '/products.SellerService/GetCategories',
                request_serializer=products__pb2.GetCategoriesRequest.SerializeToString,
                response_deserializer=products__pb2.CategoryListResponse.FromString,
                _registered_method=True)


class SellerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterItemForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnitsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItemsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=products__pb2.CreateAccountRequest.FromString,
                    response_serializer=products__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=products__pb2.LoginRequest.FromString,
                    response_serializer=products__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=products__pb2.LogoutRequest.FromString,
                    response_serializer=products__pb2.LogoutResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=products__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=products__pb2.RatingResponse.SerializeToString,
            ),
            'RegisterItemForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItemForSale,
                    request_deserializer=products__pb2.RegisterItemRequest.FromString,
                    response_serializer=products__pb2.RegisterItemResponse.SerializeToString,
            ),
            'ChangeItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeItemPrice,
                    request_deserializer=products__pb2.ChangeItemPriceRequest.FromString,
                    response_serializer=products__pb2.ChangeItemPriceResponse.SerializeToString,
            ),
            'UpdateUnitsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnitsForSale,
                    request_deserializer=products__pb2.UpdateUnitsRequest.FromString,
                    response_serializer=products__pb2.UpdateUnitsResponse.SerializeToString,
            ),
            'DisplayItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItemsForSale,
                    request_deserializer=products__pb2.DisplayItemsRequest.FromString,
                    response_serializer=products__pb2.ItemListResponse.SerializeToString,
            ),
            'GetCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategories,
                    request_deserializer=products__pb2.GetCategoriesRequest.FromString,
                    response_serializer=products__pb2.CategoryListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'products.SellerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('products.SellerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SellerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/CreateAccount',
            products__pb2.CreateAccountRequest.SerializeToString,
            products__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/Login',
            products__pb2.LoginRequest.SerializeToString,
            products__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/Logout',
            products__pb2.LogoutRequest.SerializeToString,
            products__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/GetSellerRating',
            products__pb2.GetSellerRatingRequest.SerializeToString,
            products__pb2.RatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterItemForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/RegisterItemForSale',
            products__pb2.RegisterItemRequest.SerializeToString,
            products__pb2.RegisterItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/ChangeItemPrice',
            products__pb2.ChangeItemPriceRequest.SerializeToString,
            products__pb2.ChangeItemPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnitsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/UpdateUnitsForSale',
            products__pb2.UpdateUnitsRequest.SerializeToString,
            products__pb2.UpdateUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/DisplayItemsForSale',
            products__pb2.DisplayItemsRequest.SerializeToString,
            products__pb2.ItemListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/products.SellerService/GetCategories',
            products__pb2.GetCategoriesRequest.SerializeToString,
            products__pb2.CategoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
