import logging
import datetime
import time

from pysyncobj import SyncObj, SyncObjConf, replicated

logger = logging.getLogger(__name__)


class ProductsRaft(SyncObj):
    def __init__(self, self_addr: str, partner_addrs: list, cfg: SyncObjConf):
        super().__init__(self_addr, partner_addrs, cfg)
        logger.info(
            "[raft] ProductsRaft initialised — self=%s partners=%s",
            self_addr,
            partner_addrs,
        )

    # ── Write handlers ────────────────────────────────────────────────────────
    # All ID arguments (seller_id, session_id, item_id) are pre-generated by
    # the caller so every replica inserts the same value.

    @replicated
    def create_account(self, seller_id, name, username, password):
        from proto import products_pb2
        from db import Seller
        from sqlalchemy.orm import Session
        from sqlalchemy.exc import IntegrityError
        from utils import products_engine

        t0 = time.monotonic()
        logger.debug(
            "[raft] create_account — seller_id=%s username=%r", seller_id, username
        )

        with Session(products_engine) as s:
            try:
                obj = Seller(
                    id=seller_id, name=name, username=username, password=password
                )
                s.add(obj)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] create_account OK — seller_id=%s username=%r (%.1f ms)",
                    seller_id,
                    username,
                    ms,
                )
                return products_pb2.CreateAccountResponse(
                    success=True, seller_id=seller_id
                )
            except IntegrityError:
                s.rollback()
                logger.warning(
                    "[raft] create_account CONFLICT — username=%r already exists",
                    username,
                )
                return products_pb2.CreateAccountResponse(
                    success=False, message="Account already exists"
                )
            except Exception as e:
                s.rollback()
                logger.exception(
                    "[raft] create_account ERROR — seller_id=%s: %s", seller_id, e
                )
                return products_pb2.CreateAccountResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def login(self, session_id, username, password):
        from proto import products_pb2
        from db import Seller, Session as TblSession
        from sqlalchemy.orm import Session
        from utils import products_engine

        t0 = time.monotonic()
        logger.debug("[raft] login — username=%r session_id=%s", username, session_id)

        with Session(products_engine) as s:
            seller = s.query(Seller).filter_by(username=username).first()
            if seller is None:
                logger.warning("[raft] login FAILED — username=%r not found", username)
                return products_pb2.LoginResponse(
                    success=False, message="Seller not found"
                )
            if seller.password != password:
                logger.warning(
                    "[raft] login FAILED — username=%r wrong password", username
                )
                return products_pb2.LoginResponse(
                    success=False, message="Invalid username or password"
                )
            try:
                sess = TblSession(
                    id=session_id,
                    seller_id=seller.id,
                    last_activity=datetime.datetime.now(datetime.timezone.utc),
                )
                s.add(sess)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] login OK — username=%r seller_id=%s session_id=%s (%.1f ms)",
                    username,
                    seller.id,
                    session_id,
                    ms,
                )
                return products_pb2.LoginResponse(success=True, session_id=session_id)
            except Exception as e:
                s.rollback()
                logger.exception("[raft] login ERROR — username=%r: %s", username, e)
                return products_pb2.LoginResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def logout(self, session_id):
        from proto import products_pb2
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        t0 = time.monotonic()
        logger.debug("[raft] logout — session_id=%s", session_id)

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                logger.warning(
                    "[raft] logout FAILED — session_id=%s: %s", session_id, result.error
                )
                return products_pb2.LogoutResponse(success=False, message=result.error)
            try:
                s.delete(result.session)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] logout OK — session_id=%s (%.1f ms)", session_id, ms
                )
                return products_pb2.LogoutResponse(success=True)
            except Exception as e:
                s.rollback()
                logger.exception(
                    "[raft] logout ERROR — session_id=%s: %s", session_id, e
                )
                return products_pb2.LogoutResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def register_item(
        self,
        item_id,
        session_id,
        item_name,
        category_id,
        keywords,
        condition,
        price,
        quantity,
    ):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        t0 = time.monotonic()
        logger.debug(
            "[raft] register_item — item_id=%s session_id=%s name=%r price=%s qty=%s",
            item_id,
            session_id,
            item_name,
            price,
            quantity,
        )

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                logger.warning(
                    "[raft] register_item FAILED — session_id=%s: %s",
                    session_id,
                    result.error,
                )
                return products_pb2.RegisterItemResponse(
                    success=False, message=result.error
                )
            try:
                item = Item(
                    id=item_id,
                    name=item_name,
                    category_id=category_id,
                    keywords=keywords,
                    condition=condition,
                    sale_price=price,
                    quantity=quantity,
                    seller_id=result.session.seller_id,
                )
                s.add(item)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] register_item OK — item_id=%s name=%r seller_id=%s (%.1f ms)",
                    item_id,
                    item_name,
                    result.session.seller_id,
                    ms,
                )
                return products_pb2.RegisterItemResponse(success=True, item_id=item_id)
            except Exception as e:
                s.rollback()
                logger.exception(
                    "[raft] register_item ERROR — item_id=%s: %s", item_id, e
                )
                return products_pb2.RegisterItemResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def change_price(self, session_id, item_id, new_price):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        t0 = time.monotonic()
        logger.debug(
            "[raft] change_price — item_id=%s session_id=%s new_price=%s",
            item_id,
            session_id,
            new_price,
        )

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                logger.warning(
                    "[raft] change_price FAILED — session_id=%s: %s",
                    session_id,
                    result.error,
                )
                return products_pb2.ChangeItemPriceResponse(
                    success=False, message=result.error
                )
            item = (
                s.query(Item)
                .filter_by(id=item_id, seller_id=result.session.seller_id)
                .first()
            )
            if item is None:
                logger.warning(
                    "[raft] change_price FAILED — item_id=%s not found for seller_id=%s",
                    item_id,
                    result.session.seller_id,
                )
                return products_pb2.ChangeItemPriceResponse(
                    success=False, message="Item not found"
                )
            try:
                old_price = item.sale_price
                item.sale_price = float(new_price)
                s.add(item)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] change_price OK — item_id=%s %.4f → %.4f (%.1f ms)",
                    item_id,
                    old_price,
                    item.sale_price,
                    ms,
                )
                return products_pb2.ChangeItemPriceResponse(
                    success=True, current_price=item.sale_price
                )
            except Exception as e:
                s.rollback()
                logger.exception(
                    "[raft] change_price ERROR — item_id=%s: %s", item_id, e
                )
                return products_pb2.ChangeItemPriceResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def update_units(self, session_id, item_id, new_quantity):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        t0 = time.monotonic()
        logger.debug(
            "[raft] update_units — item_id=%s session_id=%s new_quantity=%s",
            item_id,
            session_id,
            new_quantity,
        )

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                logger.warning(
                    "[raft] update_units FAILED — session_id=%s: %s",
                    session_id,
                    result.error,
                )
                return products_pb2.UpdateUnitsResponse(
                    success=False, message=result.error
                )
            item = (
                s.query(Item)
                .filter_by(id=item_id, seller_id=result.session.seller_id)
                .first()
            )
            if item is None:
                logger.warning(
                    "[raft] update_units FAILED — item_id=%s not found for seller_id=%s",
                    item_id,
                    result.session.seller_id,
                )
                return products_pb2.UpdateUnitsResponse(
                    success=False, message="Item not found"
                )
            try:
                old_qty = item.quantity
                item.quantity = int(new_quantity)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] update_units OK — item_id=%s %d → %d (%.1f ms)",
                    item_id,
                    old_qty,
                    item.quantity,
                    ms,
                )
                return products_pb2.UpdateUnitsResponse(
                    success=True, current_quantity=item.quantity
                )
            except Exception as e:
                s.rollback()
                logger.exception(
                    "[raft] update_units ERROR — item_id=%s: %s", item_id, e
                )
                return products_pb2.UpdateUnitsResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def provide_feedback(self, item_id, feedback):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from sqlalchemy.orm import joinedload
        from utils import products_engine

        t0 = time.monotonic()
        logger.debug(
            "[raft] provide_feedback — item_id=%s feedback=%s", item_id, feedback
        )

        with Session(products_engine) as s:
            item = (
                s.query(Item)
                .options(joinedload(Item.seller))
                .filter_by(id=item_id)
                .first()
            )
            if item is None:
                logger.warning(
                    "[raft] provide_feedback FAILED — item_id=%s not found", item_id
                )
                return products_pb2.ProvideFeedbackResponse(
                    success=False, message="Item not found"
                )
            item.feedback += feedback
            item.seller.feedback += feedback
            try:
                s.add(item)
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] provide_feedback OK — item_id=%s delta=%s (%.1f ms)",
                    item_id,
                    feedback,
                    ms,
                )
                return products_pb2.ProvideFeedbackResponse(success=True)
            except Exception as e:
                s.rollback()
                logger.exception(
                    "[raft] provide_feedback ERROR — item_id=%s: %s", item_id, e
                )
                return products_pb2.ProvideFeedbackResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def make_purchase(self, items):
        """items: list of (item_id, quantity) tuples"""
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from sqlalchemy.orm import joinedload

        from utils import products_engine

        t0 = time.monotonic()
        logger.debug("[raft] make_purchase — items=%s", items)

        with Session(products_engine) as s:
            try:
                for item_id, qty in items:
                    item = (
                        s.query(Item)
                        .options(joinedload(Item.seller))
                        .filter_by(id=item_id)
                        .first()
                    )
                    if item is None:
                        s.rollback()
                        logger.warning(
                            "[raft] make_purchase FAILED — item_id=%s not found",
                            item_id,
                        )
                        return products_pb2.MakePurchaseResponse(
                            success=False, message=f"Item {item_id} not found"
                        )
                    if item.quantity < qty:
                        s.rollback()
                        logger.warning(
                            "[raft] make_purchase FAILED — item_id=%s insufficient qty (have=%d want=%d)",
                            item_id,
                            item.quantity,
                            qty,
                        )
                        return products_pb2.MakePurchaseResponse(
                            success=False,
                            message=f"Insufficient quantity for {item.name}",
                        )
                    logger.debug(
                        "[raft] make_purchase deducting item_id=%s qty=%d (stock %d → %d)",
                        item_id,
                        qty,
                        item.quantity,
                        item.quantity - qty,
                    )
                    item.quantity -= qty
                    item.seller.items_sold += qty
                s.commit()
                ms = (time.monotonic() - t0) * 1000
                logger.info(
                    "[raft] make_purchase OK — %d line(s) committed (%.1f ms)",
                    len(items),
                    ms,
                )
                return products_pb2.MakePurchaseResponse(
                    success=True, message="Purchase successful"
                )
            except Exception as e:
                s.rollback()
                logger.exception("[raft] make_purchase ERROR: %s", e)
                return products_pb2.MakePurchaseResponse(
                    success=False, message=f"Database error: {e}"
                )


class RaftMixin:
    _raft: ProductsRaft


def setup_raft(member_id: int, peer_addrs: list, api) -> ProductsRaft:
    self_addr = peer_addrs[member_id]
    partners = [a for i, a in enumerate(peer_addrs) if i != member_id]
    cfg = SyncObjConf(
        autoTick=True,
        appendEntriesPeriod=0.005,  # default is 0.05
        appendEntriesRetryTime=0.05,
        raftMinTimeout=0.02,  # must be > appendEntriesPeriod * 3 (0.02 * 3 = 0.06)
        raftMaxTimeout=0.3,
        connectionRetryTime=1.0,
        logCompactionMinTime=300,
        fullDump=None,
    )
    logger.info(
        "[raft] setup_raft — member_id=%d self=%s partners=%s",
        member_id,
        self_addr,
        partners,
    )
    raft = ProductsRaft(self_addr, partners, cfg)
    api._raft = raft
    logger.info(
        "[raft] Raft node %d started — self=%s  partners=%s",
        member_id,
        self_addr,
        partners,
    )
    return raft
