"""
raft/products_raft.py — Raft replication shim for the products/seller service

KEY DESIGN RULE — pre-generated IDs:
  Each postgres instance has its own auto-increment sequence, so letting the DB
  assign IDs would produce different values on each node for the same logical
  row.  Instead, every @replicated method that creates a row receives the ID as
  an explicit argument, generated by the caller (server.py) BEFORE the Raft
  call.  Every node then does INSERT with that specific ID, keeping all DBs
  identical.

  ID generation strategy:
    seller_id   — random positive int (secrets.randbelow)
    session_id  — random positive int
    item_id     — random positive int

  The DB columns must have their server-side default removed (or be declared
  with no default) so SQLAlchemy uses the supplied value instead of letting
  postgres assign one.  Primary key columns still enforce uniqueness.
"""

import logging
import datetime

from pysyncobj import SyncObj, SyncObjConf, replicated

logger = logging.getLogger(__name__)


class ProductsRaft(SyncObj):
    def __init__(self, self_addr: str, partner_addrs: list, cfg: SyncObjConf):
        super().__init__(self_addr, partner_addrs, cfg)

    # ── Write handlers ────────────────────────────────────────────────────────
    # All ID arguments (seller_id, session_id, item_id) are pre-generated by
    # the caller so every replica inserts the same value.

    @replicated
    def create_account(self, seller_id, name, username, password):
        from proto import products_pb2
        from db import Seller
        from sqlalchemy.orm import Session
        from sqlalchemy.exc import IntegrityError
        from utils import products_engine

        with Session(products_engine) as s:
            try:
                obj = Seller(
                    id=seller_id, name=name, username=username, password=password
                )
                s.add(obj)
                s.commit()
                return products_pb2.CreateAccountResponse(
                    success=True, seller_id=seller_id
                )
            except IntegrityError:
                s.rollback()
                return products_pb2.CreateAccountResponse(
                    success=False, message="Account already exists"
                )
            except Exception as e:
                s.rollback()
                return products_pb2.CreateAccountResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def login(self, session_id, username, password):
        from proto import products_pb2
        from db import Seller, Session as TblSession
        from sqlalchemy.orm import Session
        from utils import products_engine

        with Session(products_engine) as s:
            seller = s.query(Seller).filter_by(username=username).first()
            if seller is None:
                return products_pb2.LoginResponse(
                    success=False, message="Seller not found"
                )
            if seller.password != password:
                return products_pb2.LoginResponse(
                    success=False, message="Invalid username or password"
                )
            try:
                sess = TblSession(
                    id=session_id,
                    seller_id=seller.id,
                    last_activity=datetime.datetime.now(datetime.timezone.utc),
                )
                s.add(sess)
                s.commit()
                return products_pb2.LoginResponse(success=True, session_id=session_id)
            except Exception as e:
                s.rollback()
                return products_pb2.LoginResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def logout(self, session_id):
        from proto import products_pb2
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                return products_pb2.LogoutResponse(success=False, message=result.error)
            try:
                s.delete(result.session)
                s.commit()
                return products_pb2.LogoutResponse(success=True)
            except Exception as e:
                s.rollback()
                return products_pb2.LogoutResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def register_item(
        self,
        item_id,
        session_id,
        item_name,
        category_id,
        keywords,
        condition,
        price,
        quantity,
    ):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                return products_pb2.RegisterItemResponse(
                    success=False, message=result.error
                )
            try:
                item = Item(
                    id=item_id,
                    name=item_name,
                    category_id=category_id,
                    keywords=keywords,
                    condition=condition,
                    sale_price=price,
                    quantity=quantity,
                    seller_id=result.session.seller_id,
                )
                s.add(item)
                s.commit()
                return products_pb2.RegisterItemResponse(success=True, item_id=item_id)
            except Exception as e:
                s.rollback()
                return products_pb2.RegisterItemResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def change_price(self, session_id, item_id, new_price):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                return products_pb2.ChangeItemPriceResponse(
                    success=False, message=result.error
                )
            item = (
                s.query(Item)
                .filter_by(id=item_id, seller_id=result.session.seller_id)
                .first()
            )
            if item is None:
                return products_pb2.ChangeItemPriceResponse(
                    success=False, message="Item not found"
                )
            try:
                item.sale_price = float(new_price)
                s.add(item)
                s.commit()
                return products_pb2.ChangeItemPriceResponse(
                    success=True, current_price=item.sale_price
                )
            except Exception as e:
                s.rollback()
                return products_pb2.ChangeItemPriceResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def update_units(self, session_id, item_id, new_quantity):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine, getAndValidateSession

        with Session(products_engine) as s:
            result = getAndValidateSession(session_id, s)
            if result.error:
                return products_pb2.UpdateUnitsResponse(
                    success=False, message=result.error
                )
            item = (
                s.query(Item)
                .filter_by(id=item_id, seller_id=result.session.seller_id)
                .first()
            )
            if item is None:
                return products_pb2.UpdateUnitsResponse(
                    success=False, message="Item not found"
                )
            try:
                item.quantity = int(new_quantity)
                s.commit()
                return products_pb2.UpdateUnitsResponse(
                    success=True, current_quantity=item.quantity
                )
            except Exception as e:
                s.rollback()
                return products_pb2.UpdateUnitsResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def provide_feedback(self, item_id, feedback):
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine

        with Session(products_engine) as s:
            item = s.query(Item).filter_by(id=item_id).first()
            if item is None:
                return products_pb2.ProvideFeedbackResponse(
                    success=False, message="Item not found"
                )
            item.feedback += feedback
            item.seller.feedback += feedback
            try:
                s.add(item)
                s.commit()
                return products_pb2.ProvideFeedbackResponse(success=True)
            except Exception as e:
                s.rollback()
                return products_pb2.ProvideFeedbackResponse(
                    success=False, message=f"Database error: {e}"
                )

    @replicated
    def make_purchase(self, items):
        """items: list of (item_id, quantity) tuples"""
        from proto import products_pb2
        from db import Item
        from sqlalchemy.orm import Session
        from utils import products_engine

        with Session(products_engine) as s:
            try:
                for item_id, qty in items:
                    item = s.query(Item).filter_by(id=item_id).first()
                    if item is None:
                        s.rollback()
                        return products_pb2.MakePurchaseResponse(
                            success=False, message=f"Item {item_id} not found"
                        )
                    if item.quantity < qty:
                        s.rollback()
                        return products_pb2.MakePurchaseResponse(
                            success=False,
                            message=f"Insufficient quantity for {item.name}",
                        )
                    item.quantity -= qty
                    item.seller.items_sold += qty
                s.commit()
                return products_pb2.MakePurchaseResponse(
                    success=True, message="Purchase successful"
                )
            except Exception as e:
                s.rollback()
                return products_pb2.MakePurchaseResponse(
                    success=False, message=f"Database error: {e}"
                )


class RaftMixin:
    _raft: ProductsRaft


def setup_raft(member_id: int, peer_addrs: list, api) -> ProductsRaft:
    self_addr = peer_addrs[member_id]
    partners = [a for i, a in enumerate(peer_addrs) if i != member_id]
    cfg = SyncObjConf(
        autoTick=True,
        appendEntriesRetryTime=0.5,
        raftMinTimeout=1.5,
        raftMaxTimeout=3.0,
        connectionRetryTime=5.0,
        logCompactionMinTime=300,
        fullDump=None,
    )
    raft = ProductsRaft(self_addr, partners, cfg)
    api._raft = raft
    logger.info(
        "Raft node %d started — self=%s  partners=%s", member_id, self_addr, partners
    )
    return raft
