# NAME               NETWORK_IP
# customer-frontend  10.180.0.20
# customers-rpc-0    10.180.0.15
# customers-rpc-1    10.180.0.16
# customers-rpc-2    10.180.0.17
# customers-rpc-3    10.180.0.18
# customers-rpc-4    10.180.0.19
# payment-api        10.180.0.22
# products-rpc-0     10.180.0.10
# products-rpc-1     10.180.0.11
# products-rpc-2     10.180.0.12
# products-rpc-3     10.180.0.13
# products-rpc-4     10.180.0.14
# seller-frontend    10.180.0.21

all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/gcp-ansible-key
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyCommand='gcloud compute start-iap-tunnel %h 22 --listen-on-stdin --zone=us-west3-a --project=distributed-systems-487323'"
    ansible_user: hamad
  children:
    frontends:
      vars:
        container_env:
          CUSTOMERS_RPC_ADDRS: "10.180.0.15:5000,10.180.0.16:5000,10.180.0.17:5000,10.180.0.18:5000,10.180.0.19:5000"
          PRODUCTS_RPC_ADDRS: "10.180.0.10:5000,10.180.0.11:5000,10.180.0.12:5000,10.180.0.13:5000,10.180.0.14:5000"
          WSDL_PAYMENT_HOST: "10.180.0.22"
          WSDL_PAYMENT_PORT: "80"
      hosts:
        customer-frontend:
          service: buyer-frontend
          service_ports:
            - "80:5000"
        seller-frontend:
          service: seller-frontend
          service_ports:
            - "80:5000"
    rpcs:
      hosts:
        customers-rpc-0:
          service: customers-database
          service_ports:
            - "5000:5000"
            - "7000:7000/udp"
          container_env:
            PEER_ADDRS: "10.180.0.15:7000,10.180.0.16:7000,10.180.0.17:7000,10.180.0.18:7000,10.180.0.19:7000"
            DB_NAME: "customers"
            MEMBER_ID: "0"
            N_MEMBERS: "5"
        customers-rpc-1:
          service: customers-database
          service_ports:
            - "5000:5000"
            - "7000:7000/udp"
          container_env:
            PEER_ADDRS: "10.180.0.15:7000,10.180.0.16:7000,10.180.0.17:7000,10.180.0.18:7000,10.180.0.19:7000"
            DB_NAME: "customers"
            MEMBER_ID: "1"
            N_MEMBERS: "5"
        customers-rpc-2:
          service: customers-database
          service_ports:
            - "5000:5000"
            - "7000:7000/udp"
          container_env:
            PEER_ADDRS: "10.180.0.15:7000,10.180.0.16:7000,10.180.0.17:7000,10.180.0.18:7000,10.180.0.19:7000"
            DB_NAME: "customers"
            MEMBER_ID: "2"
            N_MEMBERS: "5"
        customers-rpc-3:
          service: customers-database
          service_ports:
            - "5000:5000"
            - "7000:7000/udp"
          container_env:
            PEER_ADDRS: "10.180.0.15:7000,10.180.0.16:7000,10.180.0.17:7000,10.180.0.18:7000,10.180.0.19:7000"
            DB_NAME: "customers"
            MEMBER_ID: "3"
            N_MEMBERS: "5"
        customers-rpc-4:
          service: customers-database
          service_ports:
            - "5000:5000"
            - "7000:7000/udp"
          container_env:
            PEER_ADDRS: "10.180.0.15:7000,10.180.0.16:7000,10.180.0.17:7000,10.180.0.18:7000,10.180.0.19:7000"
            DB_NAME: "customers"
            MEMBER_ID: "4"
            N_MEMBERS: "5"
        products-rpc-0:
          service: products-database
          service_ports:
            - "5000:5000"
            - "7000:7000"
          container_env:
            MEMBER_ID: "0"
            DB_NAME: "products"
            RAFT_ADDRS: "10.180.0.10:7000,10.180.0.11:7000,10.180.0.12:7000,10.180.0.13:7000,10.180.0.14:7000"
        products-rpc-1:
          service: products-database
          service_ports:
            - "5000:5000"
            - "7000:7000"
          container_env:
            MEMBER_ID: "1"
            DB_NAME: "products"
            RAFT_ADDRS: "10.180.0.10:7000,10.180.0.11:7000,10.180.0.12:7000,10.180.0.13:7000,10.180.0.14:7000"
        products-rpc-2:
          service: products-database
          service_ports:
            - "5000:5000"
            - "7000:7000"
          container_env:
            MEMBER_ID: "2"
            DB_NAME: "products"
            RAFT_ADDRS: "10.180.0.10:7000,10.180.0.11:7000,10.180.0.12:7000,10.180.0.13:7000,10.180.0.14:7000"
        products-rpc-3:
          service: products-database
          service_ports:
            - "5000:5000"
            - "7000:7000"
          container_env:
            MEMBER_ID: "3"
            DB_NAME: "products"
            RAFT_ADDRS: "10.180.0.10:7000,10.180.0.11:7000,10.180.0.12:7000,10.180.0.13:7000,10.180.0.14:7000"
        products-rpc-4:
          service: products-database
          service_ports:
            - "5000:5000"
            - "7000:7000"
          container_env:
            MEMBER_ID: "4"
            DB_NAME: "products"
            RAFT_ADDRS: "10.180.0.10:7000,10.180.0.11:7000,10.180.0.12:7000,10.180.0.13:7000,10.180.0.14:7000"

    payments:
      hosts:
        payments-api:
          service: payments-api
          service_ports:
            - "80:5000"
