# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import customers_pb2 as customers__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
                '/customers.CustomersService/CreateAccount',
                request_serializer=customers__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=customers__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/customers.CustomersService/Login',
                request_serializer=customers__pb2.LoginRequest.SerializeToString,
                response_deserializer=customers__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/customers.CustomersService/Logout',
                request_serializer=customers__pb2.LogoutRequest.SerializeToString,
                response_deserializer=customers__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.AddItemToCart = channel.unary_unary(
                '/customers.CustomersService/AddItemToCart',
                request_serializer=customers__pb2.AddItemToCartRequest.SerializeToString,
                response_deserializer=customers__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.RemoveItemFromCart = channel.unary_unary(
                '/customers.CustomersService/RemoveItemFromCart',
                request_serializer=customers__pb2.RemoveItemFromCartRequest.SerializeToString,
                response_deserializer=customers__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/customers.CustomersService/ClearCart',
                request_serializer=customers__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=customers__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/customers.CustomersService/SaveCart',
                request_serializer=customers__pb2.SaveCartRequest.SerializeToString,
                response_deserializer=customers__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/customers.CustomersService/GetCart',
                request_serializer=customers__pb2.GetCartRequest.SerializeToString,
                response_deserializer=customers__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/customers.CustomersService/GetBuyerPurchases',
                request_serializer=customers__pb2.GetBuyerPurchasesRequest.SerializeToString,
                response_deserializer=customers__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)
        self.GetBuyer = channel.unary_unary(
                '/customers.CustomersService/GetBuyer',
                request_serializer=customers__pb2.GetBuyerRequest.SerializeToString,
                response_deserializer=customers__pb2.GetBuyerResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/customers.CustomersService/MakePurchase',
                request_serializer=customers__pb2.MakePurchaseRequest.SerializeToString,
                response_deserializer=customers__pb2.MakePurchaseResponse.FromString,
                _registered_method=True)


class CustomersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItemToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItemFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=customers__pb2.CreateAccountRequest.FromString,
                    response_serializer=customers__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=customers__pb2.LoginRequest.FromString,
                    response_serializer=customers__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=customers__pb2.LogoutRequest.FromString,
                    response_serializer=customers__pb2.BasicResponse.SerializeToString,
            ),
            'AddItemToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItemToCart,
                    request_deserializer=customers__pb2.AddItemToCartRequest.FromString,
                    response_serializer=customers__pb2.BasicResponse.SerializeToString,
            ),
            'RemoveItemFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItemFromCart,
                    request_deserializer=customers__pb2.RemoveItemFromCartRequest.FromString,
                    response_serializer=customers__pb2.BasicResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=customers__pb2.ClearCartRequest.FromString,
                    response_serializer=customers__pb2.BasicResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=customers__pb2.SaveCartRequest.FromString,
                    response_serializer=customers__pb2.BasicResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=customers__pb2.GetCartRequest.FromString,
                    response_serializer=customers__pb2.GetCartResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=customers__pb2.GetBuyerPurchasesRequest.FromString,
                    response_serializer=customers__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
            'GetBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyer,
                    request_deserializer=customers__pb2.GetBuyerRequest.FromString,
                    response_serializer=customers__pb2.GetBuyerResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=customers__pb2.MakePurchaseRequest.FromString,
                    response_serializer=customers__pb2.MakePurchaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customers.CustomersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('customers.CustomersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/CreateAccount',
            customers__pb2.CreateAccountRequest.SerializeToString,
            customers__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/Login',
            customers__pb2.LoginRequest.SerializeToString,
            customers__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/Logout',
            customers__pb2.LogoutRequest.SerializeToString,
            customers__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItemToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/AddItemToCart',
            customers__pb2.AddItemToCartRequest.SerializeToString,
            customers__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveItemFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/RemoveItemFromCart',
            customers__pb2.RemoveItemFromCartRequest.SerializeToString,
            customers__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/ClearCart',
            customers__pb2.ClearCartRequest.SerializeToString,
            customers__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/SaveCart',
            customers__pb2.SaveCartRequest.SerializeToString,
            customers__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/GetCart',
            customers__pb2.GetCartRequest.SerializeToString,
            customers__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/GetBuyerPurchases',
            customers__pb2.GetBuyerPurchasesRequest.SerializeToString,
            customers__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/GetBuyer',
            customers__pb2.GetBuyerRequest.SerializeToString,
            customers__pb2.GetBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customers.CustomersService/MakePurchase',
            customers__pb2.MakePurchaseRequest.SerializeToString,
            customers__pb2.MakePurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
